### PR TITLE
import/export styles, MobX additions 

### PR DESCRIPTION
**Pull request by arackaf**
I sent you a note on Twitter, but I don't know how often you check that.  Basically, this adds mobx helpers: sfc's and class components, both with observer applied. 

I also changed some styling, basically moving the `export default` up inline with the class / arrow definition, to cut down on some boilerplate. I moved SFCs to be inline, with a new option to spit one out with braces.

Also plan to add more mobx goodies, class action methods/properties, computed properties, etc.

If you don't want these changes then totally fine - I'm happy to just have them be local, for myself.  But wanted to at least give you the choice :)

### CODE REVIEW

**Comment by arackaf** [comment]
Gah - the descriptions are off - sorry - fixing now

**Comment by arackaf** [comment]
@xabikos - hi, no rush on approving the PR at all, I'm just wondering if you can just let me know if you're interested these additions / changes.  If this isn't a direction you wanna take your project, that's cool - I'm happy to have GitHub convert my fork to be my own repo (giving you credit, of course) and keep on pressing forward. 

Just wanna know either way :)

**Comment by arackaf** [comment]
@xabikos sorry to bother again - just wanna ping you one last time to see if you're interested in these changes I've got going - if I don't hear back, I'll probably just press forward with my own fork - I'll be sure to give you credit in my readme, of course.

**Comment by xabikos** [comment]
@arackaf my apologies for the late reply.

Thank you very much for the PR you did an awesome job. But I think it's better to publish it as a completely different extension for the editor rather than merge it with this. By doing this you will have full control on how it should look like.

Let me explain the reasons why I am saying that. 
- I would prefer to keep this extension to be pure React and not mix it with any state management library. For this reason I haven't included any `Redux` snippets for example. There are several additional extensions for [Redux](https://marketplace.visualstudio.com/search?term=redux&target=VSCode&category=Snippets&sortBy=Relevance) as you can see but not for [MobX](https://marketplace.visualstudio.com/search?term=mobx&target=VSCode&category=Snippets&sortBy=Relevance)
- The change you made with removing explicit export and merge it one line is a matter of taste. When I created the snippets I thought a lot about it and how it should be done. Whatever the choice some of us will like it and some not. So Once there are not many requests to change it I am in favor to keep it like that. 

You have done all the work so far so it's a small additional step to publish it. Let me know if you need any help with the procedure of publishing the extension.

**Pull request closed without merging**
