### PR TITLE
Update lifecycle hooks snippets

### LINKED ISSUE #40: Add static getDerivedStateFromProps(){}
With react 16.4 , `componentWillReceiveProps` will be deprecated and `getDerivedStateFromProps` will be used

### PR DESCRIPTION
**Pull request by RusinovAnton**
2 new lifecycle hooks were added, componentWill- hooks been deprecated
in React 16.3

refs: https://github.com/facebook/react/releases/tag/v16.3.0

closes https://github.com/xabikos/vscode-react/issues/40

### CODE REVIEW

**Comment by RusinovAnton** [comment]
@xabikos 

Also we might want to add part with condition for `getSnapshotBeforeUpdate()` from example from react docs:

```js
if (${1:condition}) {
  return ${2:snapshot};
}

return null;
```

refs: https://reactjs.org/docs/react-component.html#getsnapshotbeforeupdate

**Comment by RusinovAnton** [comment]
Deprecation note could definitely use some critique.

**Review by xabikos — CHANGES_REQUESTED** [review]
@RusinovAnton thank you very much for the PR. I would happily merge it. But could you push another commit that removes the not needed white space? I would prefer to only see additions on this PR.

**Comment by RusinovAnton** [comment]
@xabikos done along with some fixes and additions

**Review by xabikos — APPROVED** [review]

**Pull request merged**
