### PR TITLE
Add jsx lang support

### PR DESCRIPTION
**Pull request by the-evgenii**

### CODE REVIEW

**Comment by xabikos** [comment]
Thanks for the pull request but I am a bit confused about the goal. VS Code currently doesn't have a jsx language but just JavaScript React. Except that I am not sure that we can have two objects defining the language of the snippets. I have to investigate more on that.

**Comment by luisrudge** [comment]
@xabikos yes it does: 

image

Currently, this snippets are not working for me. I have to change all my files to javascript react to make it work, but I'm not doing that for all of them.. Please merge this. Thanks @jmlv

**Comment by xabikos** [comment]
@luisrudge I don't know which version of Code you had but I can't find this extension in three different environments that I tried. If I am not mistaken this extension existed in the early versions of the editor.

**Comment by luisrudge** [comment]
I'm on latest:

image

It does exist now and merging this PR will make everyone's lives easier :)

**Pull request closed without merging**
